package main

import (
	"bufio"
	"context"
	"encoding/binary"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

const phase8HelperEnv = "PHOTON_PHASE8_SMOKE_HELPER"

func TestMain(m *testing.M) {
	switch os.Getenv(phase8HelperEnv) {
	case "socks5":
		os.Exit(runPhase8SOCKS5Server())
	case "echo":
		os.Exit(runPhase8EchoServer())
	case "client":
		os.Exit(runPhase8SOCKS5Client())
	default:
		os.Exit(m.Run())
	}
}

// TestSOCKS5DockerBridgeBabelRootSmoke validates the Phase 8 data path using
// the generated-service shape: a client namespace learns the service prefix
// through Babel, the host's Docker connected route wins over its broader
// host-to-overlay aggregate route, and an unpublished SOCKS5 container port is
// directly routed through the Docker bridge. It is deliberately opt-in because it
// creates network namespaces, BIRD processes, Docker containers and routes.
func TestSOCKS5DockerBridgeBabelRootSmoke(t *testing.T) {
	if os.Getenv("PHOTON_SERVICES_SMOKE") != "1" {
		t.Skip("set PHOTON_SERVICES_SMOKE=1 to run the Phase 8 Docker/Babel root smoke")
	}
	for _, binary := range []string{"ip", "bird", "birdc", "docker", "nft"} {
		if _, err := exec.LookPath(binary); err != nil {
			t.Fatalf("%s is required: %v", binary, err)
		}
	}

	ctx, cancel := context.WithTimeout(context.Background(), 75*time.Second)
	defer cancel()
	suffix := fmt.Sprintf("%06d", time.Now().UnixNano()%1_000_000)
	octet := int(time.Now().UnixNano()%200) + 20
	aggregate := fmt.Sprintf("198.18.%d.0/24", octet)
	servicePrefix := fmt.Sprintf("198.18.%d.16/28", octet)
	remotePrefix := fmt.Sprintf("198.18.%d.32/28", octet)
	serviceIP := fmt.Sprintf("198.18.%d.18", octet)
	echoIP := fmt.Sprintf("198.18.%d.19", octet)
	gatewayIP := fmt.Sprintf("198.18.%d.17", octet)
	clientIP := fmt.Sprintf("10.254.%d.2", octet)
	meshAIP := fmt.Sprintf("169.254.%d.1", octet)
	meshBIP := fmt.Sprintf("169.254.%d.2", octet)
	hostBIP := fmt.Sprintf("169.254.%d.5", octet)
	hostIP := fmt.Sprintf("169.254.%d.6", octet)

	nsA, nsB := "hp8a"+suffix, "hp8b"+suffix
	aIf, bIf := "p8a"+suffix, "p8b"+suffix
	bHostIf, hostIf := "p8m"+suffix, "p8h"+suffix
	networkName := "photon-phase8-" + suffix
	socksName, echoName := "photon-p8-socks-"+suffix, "photon-p8-echo-"+suffix
	tmp := t.TempDir()

	for _, ns := range []string{nsA, nsB} {
		runPhase8Command(t, ctx, "ip", "netns", "add", ns)
	}
	t.Cleanup(func() {
		for _, ns := range []string{nsA, nsB} {
			_ = exec.Command("ip", "netns", "delete", ns).Run()
		}
	})

	runPhase8Command(t, ctx, "ip", "link", "add", aIf, "type", "veth", "peer", "name", bIf)
	runPhase8Command(t, ctx, "ip", "link", "set", aIf, "netns", nsA)
	runPhase8Command(t, ctx, "ip", "link", "set", bIf, "netns", nsB)
	runPhase8Command(t, ctx, "ip", "link", "add", bHostIf, "type", "veth", "peer", "name", hostIf)
	runPhase8Command(t, ctx, "ip", "link", "set", bHostIf, "netns", nsB)
	t.Cleanup(func() { _ = exec.Command("ip", "link", "delete", hostIf).Run() })

	for _, ns := range []string{nsA, nsB} {
		runPhase8Command(t, ctx, "ip", "netns", "exec", ns, "ip", "link", "set", "lo", "up")
		runPhase8Command(t, ctx, "ip", "netns", "exec", ns, "sysctl", "-qw", "net.ipv4.ip_forward=1")
	}
	runPhase8Command(t, ctx, "ip", "netns", "exec", nsA, "ip", "addr", "add", meshAIP+"/30", "dev", aIf)
	runPhase8Command(t, ctx, "ip", "netns", "exec", nsA, "ip", "addr", "add", clientIP+"/32", "dev", "lo")
	runPhase8Command(t, ctx, "ip", "netns", "exec", nsA, "ip", "link", "set", aIf, "up")
	runPhase8Command(t, ctx, "ip", "netns", "exec", nsB, "ip", "addr", "add", meshBIP+"/30", "dev", bIf)
	runPhase8Command(t, ctx, "ip", "netns", "exec", nsB, "ip", "link", "set", bIf, "up")
	runPhase8Command(t, ctx, "ip", "netns", "exec", nsB, "ip", "addr", "add", hostBIP+"/30", "dev", bHostIf)
	runPhase8Command(t, ctx, "ip", "netns", "exec", nsB, "ip", "link", "set", bHostIf, "up")
	runPhase8Command(t, ctx, "ip", "addr", "add", hostIP+"/30", "dev", hostIf)
	runPhase8Command(t, ctx, "ip", "link", "set", hostIf, "up")

	previousForward := readPhase8Forwarding(t)
	if previousForward != "1" {
		runPhase8Command(t, ctx, "sysctl", "-qw", "net.ipv4.ip_forward=1")
		t.Cleanup(func() { _ = exec.Command("sysctl", "-qw", "net.ipv4.ip_forward="+previousForward).Run() })
	}
	runPhase8Command(t, ctx, "ip", "route", "replace", aggregate, "via", hostBIP)
	runPhase8Command(t, ctx, "ip", "route", "replace", clientIP+"/32", "via", hostBIP)
	t.Cleanup(func() {
		_ = exec.Command("ip", "route", "del", aggregate, "via", hostBIP).Run()
		_ = exec.Command("ip", "route", "del", clientIP+"/32", "via", hostBIP).Run()
	})

	// Use the exact bridge name generated by the Phase 8 manifest convention.
	runPhase8Command(t, ctx, "docker", "network", "create", "--driver", "bridge", "--subnet", servicePrefix, "--gateway", gatewayIP,
		"-o", "com.docker.network.bridge.trusted_host_interfaces="+hostIf,
		"-o", "com.docker.network.bridge.gateway_mode_ipv4=nat-unprotected", networkName)
	t.Cleanup(func() { _ = exec.Command("docker", "network", "rm", networkName).Run() })
	networkID, err := exec.CommandContext(ctx, "docker", "network", "inspect", "-f", "{{.Id}}", networkName).Output()
	if err != nil {
		t.Fatalf("inspect Docker network %s: %v", networkName, err)
	}
	bridgeName := "br-" + strings.TrimSpace(string(networkID))[:12]
	helperBinary, helperCopied, err := phase8DockerVisibleHelper(suffix)
	if err != nil {
		t.Fatal(err)
	}
	if helperCopied {
		t.Cleanup(func() { _ = os.Remove(helperBinary) })
	}
	runPhase8Command(t, ctx, "docker", "run", "-d", "--name", socksName, "--network", networkName, "--ip", serviceIP,
		"--mount", "type=bind,src="+helperBinary+",dst=/phase8-helper,readonly", "-e", phase8HelperEnv+"=socks5", "alpine:3", "/phase8-helper", "-test.run=TestPhase8Helper")
	t.Cleanup(func() { _ = exec.Command("docker", "rm", "-f", socksName).Run() })
	runPhase8Command(t, ctx, "docker", "run", "-d", "--name", echoName, "--network", networkName, "--ip", echoIP,
		"--mount", "type=bind,src="+helperBinary+",dst=/phase8-helper,readonly", "-e", phase8HelperEnv+"=echo", "alpine:3", "/phase8-helper", "-test.run=TestPhase8Helper")
	t.Cleanup(func() { _ = exec.Command("docker", "rm", "-f", echoName).Run() })
	// trusted_host_interfaces designates the overlay ingress veth and
	// nat-unprotected permits direct routing to unpublished container ports.
	// DOCKER-USER remains the policy point for the IP-scoped endpoint ACL.
	// Store nft handles so cleanup removes precisely these two rules.
	ruleTag := "photon-phase8-" + suffix
	allowIn := []string{"insert", "rule", "ip", "filter", "DOCKER-USER", "iifname", hostIf, "oifname", bridgeName, "ip", "daddr", serviceIP, "accept", "comment", ruleTag + "-in"}
	allowOut := []string{"insert", "rule", "ip", "filter", "DOCKER-USER", "iifname", bridgeName, "oifname", hostIf, "ip", "saddr", serviceIP, "accept", "comment", ruleTag + "-out"}
	runPhase8Command(t, ctx, "nft", allowIn...)
	runPhase8Command(t, ctx, "nft", allowOut...)
	t.Cleanup(func() {
		phase8DeleteDockerUserRule(ruleTag + "-out")
		phase8DeleteDockerUserRule(ruleTag + "-in")
	})
	if err := waitPhase8TCP(ctx, serviceIP+":3128"); err != nil {
		logs, _ := exec.CommandContext(ctx, "docker", "logs", socksName).CombinedOutput()
		t.Fatalf("%v\nSOCKS5 container logs:\n%s", err, logs)
	}

	configA := filepath.Join(tmp, "a.conf")
	configB := filepath.Join(tmp, "b.conf")
	socketA := filepath.Join(tmp, "a.ctl")
	socketB := filepath.Join(tmp, "b.ctl")
	writePhase8BirdConfig(t, configA, fmt.Sprintf(`router id 10.99.%d.1;
protocol device { scan time 1; }
protocol kernel { ipv4 { import none; export all; }; }
protocol static { ipv4; route %s reject; route %s reject; }
protocol babel mesh { ipv4 { import all; export all; }; interface %q { type tunnel; rxcost 100; hello interval 1 s; update interval 1 s; }; }
`, octet, clientIP+"/32", remotePrefix, aIf))
	writePhase8BirdConfig(t, configB, fmt.Sprintf(`router id 10.99.%d.2;
protocol device { scan time 1; }
protocol kernel { ipv4 { import none; export all; }; }
protocol static { ipv4; route %s via %s; }
protocol babel mesh { ipv4 { import all; export all; }; interface %q { type tunnel; rxcost 100; hello interval 1 s; update interval 1 s; }; }
`, octet, servicePrefix, hostIP, bIf))
	startPhase8Bird(t, ctx, nsA, configA, socketA, filepath.Join(tmp, "a.pid"))
	startPhase8Bird(t, ctx, nsB, configB, socketB, filepath.Join(tmp, "b.pid"))
	defer stopPhase8Bird(socketA)
	defer stopPhase8Bird(socketB)
	waitPhase8BirdRoute(t, ctx, socketA, servicePrefix)
	waitPhase8BirdRoute(t, ctx, socketB, clientIP+"/32")

	assertPhase8Route(t, ctx, "", serviceIP, "dev br-")
	assertPhase8Route(t, ctx, "", fmt.Sprintf("198.18.%d.34", octet), "via "+hostBIP)
	assertPhase8Route(t, ctx, nsA, serviceIP, "via "+meshBIP)
	assertPhase8Route(t, ctx, nsB, clientIP, "via "+meshAIP)

	cmd := exec.CommandContext(ctx, "ip", "netns", "exec", nsA, helperBinary, "-test.run=TestPhase8Helper")
	cmd.Env = append(os.Environ(), phase8HelperEnv+"=client", "PHOTON_PHASE8_SOCKS="+serviceIP+":3128", "PHOTON_PHASE8_ECHO="+echoIP+":8080", "PHOTON_PHASE8_SOURCE="+clientIP)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("SOCKS5 client through Babel and Docker bridge: %v\n%s", err, output)
	}
}

func runPhase8SOCKS5Server() int {
	listener, err := net.Listen("tcp", ":3128")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	for {
		conn, err := listener.Accept()
		if err != nil {
			return 1
		}
		go servePhase8SOCKS5(conn)
	}
}

func servePhase8SOCKS5(client net.Conn) {
	defer client.Close()
	_ = client.SetDeadline(time.Now().Add(10 * time.Second))
	reader := bufio.NewReader(client)
	header := make([]byte, 2)
	if _, err := io.ReadFull(reader, header); err != nil || header[0] != 5 {
		return
	}
	methods := make([]byte, int(header[1]))
	if _, err := io.ReadFull(reader, methods); err != nil {
		return
	}
	if _, err := client.Write([]byte{5, 0}); err != nil {
		return
	}
	request := make([]byte, 4)
	if _, err := io.ReadFull(reader, request); err != nil || request[0] != 5 || request[2] != 0 {
		return
	}
	target, err := readPhase8SOCKSAddress(reader, request[3])
	if err != nil {
		return
	}
	switch request[1] {
	case 1:
		servePhase8SOCKSConnect(client, reader, target)
	case 3:
		servePhase8SOCKSUDPAssociate(client)
	}
}

func servePhase8SOCKSConnect(client net.Conn, reader io.Reader, target *net.UDPAddr) {
	upstream, err := net.DialTimeout("tcp", target.String(), 5*time.Second)
	if err != nil {
		_, _ = client.Write([]byte{5, 5, 0, 1, 0, 0, 0, 0, 0, 0})
		return
	}
	defer upstream.Close()
	if _, err := client.Write([]byte{5, 0, 0, 1, 0, 0, 0, 0, 0, 0}); err != nil {
		return
	}
	_ = client.SetDeadline(time.Time{})
	go io.Copy(upstream, reader)
	_, _ = io.Copy(client, upstream)
}

func servePhase8SOCKSUDPAssociate(client net.Conn) {
	local := client.LocalAddr().(*net.TCPAddr)
	relay, err := net.ListenUDP("udp4", &net.UDPAddr{IP: local.IP.To4()})
	if err != nil {
		_, _ = client.Write([]byte{5, 5, 0, 1, 0, 0, 0, 0, 0, 0})
		return
	}
	defer relay.Close()
	relayAddr := relay.LocalAddr().(*net.UDPAddr)
	reply := phase8SOCKSUDPHeader(relayAddr)
	reply[0] = 5
	if _, err := client.Write(reply); err != nil {
		return
	}
	_ = relay.SetDeadline(time.Now().Add(10 * time.Second))
	packet := make([]byte, 65535)
	n, clientAddr, err := relay.ReadFromUDP(packet)
	if err != nil {
		return
	}
	target, payload, err := parsePhase8SOCKSUDPDatagram(packet[:n])
	if err != nil {
		return
	}
	if _, err := relay.WriteToUDP(payload, target); err != nil {
		return
	}
	n, upstreamAddr, err := relay.ReadFromUDP(packet)
	if err != nil {
		return
	}
	response := append(phase8SOCKSUDPHeader(upstreamAddr), packet[:n]...)
	_, _ = relay.WriteToUDP(response, clientAddr)
}

func readPhase8SOCKSAddress(reader io.Reader, atyp byte) (*net.UDPAddr, error) {
	var size int
	switch atyp {
	case 1:
		size = net.IPv4len
	case 4:
		size = net.IPv6len
	default:
		return nil, fmt.Errorf("unsupported SOCKS address type %d", atyp)
	}
	address := make([]byte, size+2)
	if _, err := io.ReadFull(reader, address); err != nil {
		return nil, err
	}
	return &net.UDPAddr{IP: net.IP(address[:size]), Port: int(binary.BigEndian.Uint16(address[size:]))}, nil
}

func phase8SOCKSUDPHeader(address *net.UDPAddr) []byte {
	ip := address.IP.To4()
	header := []byte{0, 0, 0, 1}
	header = append(header, ip...)
	return binary.BigEndian.AppendUint16(header, uint16(address.Port))
}

func parsePhase8SOCKSUDPDatagram(packet []byte) (*net.UDPAddr, []byte, error) {
	if len(packet) < 10 || packet[0] != 0 || packet[1] != 0 || packet[2] != 0 {
		return nil, nil, fmt.Errorf("invalid SOCKS UDP header")
	}
	target, err := readPhase8SOCKSAddress(strings.NewReader(string(packet[4:])), packet[3])
	if err != nil {
		return nil, nil, err
	}
	headerSize := 4 + net.IPv4len + 2
	if packet[3] == 4 {
		headerSize = 4 + net.IPv6len + 2
	}
	return target, packet[headerSize:], nil
}

func runPhase8EchoServer() int {
	udp, err := net.ListenUDP("udp4", &net.UDPAddr{Port: 8080})
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	defer udp.Close()
	go servePhase8DNSServer(udp)

	listener, err := net.Listen("tcp", ":8080")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	for {
		conn, err := listener.Accept()
		if err != nil {
			return 1
		}
		go func() {
			defer conn.Close()
			buf := make([]byte, 4)
			if _, err := io.ReadFull(conn, buf); err == nil && string(buf) == "ping" {
				_, _ = io.WriteString(conn, "phase8-ok")
			}
		}()
	}
}

func servePhase8DNSServer(conn *net.UDPConn) {
	packet := make([]byte, 512)
	for {
		n, peer, err := conn.ReadFromUDP(packet)
		if err != nil {
			return
		}
		response, err := phase8DNSResponse(packet[:n])
		if err == nil {
			_, _ = conn.WriteToUDP(response, peer)
		}
	}
}

func phase8DNSResponse(query []byte) ([]byte, error) {
	if len(query) < 12 {
		return nil, fmt.Errorf("short DNS query")
	}
	response := append([]byte(nil), query...)
	response[2], response[3] = 0x81, 0x80
	response[6], response[7] = 0, 2
	answer := func(address byte) []byte {
		return []byte{0xc0, 0x0c, 0, 1, 0, 1, 0, 0, 0, 60, 0, 4, 192, 0, 2, address}
	}
	response = append(response, answer(1)...)
	response = append(response, answer(2)...)
	return response, nil
}

func runPhase8SOCKS5Client() int {
	source := net.ParseIP(os.Getenv("PHOTON_PHASE8_SOURCE"))
	conn, err := (&net.Dialer{Timeout: 10 * time.Second, LocalAddr: &net.TCPAddr{IP: source}}).Dial("tcp", os.Getenv("PHOTON_PHASE8_SOCKS"))
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	defer conn.Close()
	if _, err := conn.Write([]byte{5, 1, 0}); err != nil {
		return 1
	}
	response := make([]byte, 2)
	if _, err := io.ReadFull(conn, response); err != nil || string(response) != string([]byte{5, 0}) {
		return 1
	}
	host, portText, err := net.SplitHostPort(os.Getenv("PHOTON_PHASE8_ECHO"))
	if err != nil {
		return 1
	}
	port, err := net.LookupPort("tcp", portText)
	if err != nil {
		return 1
	}
	addr := net.ParseIP(host).To4()
	request := append([]byte{5, 1, 0, 1}, addr...)
	request = binary.BigEndian.AppendUint16(request, uint16(port))
	if _, err := conn.Write(request); err != nil {
		return 1
	}
	reply := make([]byte, 10)
	if _, err := io.ReadFull(conn, reply); err != nil || reply[1] != 0 {
		return 1
	}
	if _, err := io.WriteString(conn, "ping"); err != nil {
		return 1
	}
	result := make([]byte, len("phase8-ok"))
	if _, err := io.ReadFull(conn, result); err != nil || string(result) != "phase8-ok" {
		return 1
	}
	if err := conn.Close(); err != nil {
		return 1
	}
	if err := runPhase8SOCKS5UDPClient(source); err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	return 0
}

func runPhase8SOCKS5UDPClient(source net.IP) error {
	control, err := (&net.Dialer{Timeout: 10 * time.Second, LocalAddr: &net.TCPAddr{IP: source}}).Dial("tcp", os.Getenv("PHOTON_PHASE8_SOCKS"))
	if err != nil {
		return err
	}
	defer control.Close()
	if _, err := control.Write([]byte{5, 1, 0}); err != nil {
		return err
	}
	greeting := make([]byte, 2)
	if _, err := io.ReadFull(control, greeting); err != nil || string(greeting) != string([]byte{5, 0}) {
		return fmt.Errorf("SOCKS UDP greeting failed: %v, %v", greeting, err)
	}
	if _, err := control.Write([]byte{5, 3, 0, 1, 0, 0, 0, 0, 0, 0}); err != nil {
		return err
	}
	reply := make([]byte, 10)
	if _, err := io.ReadFull(control, reply); err != nil || reply[1] != 0 || reply[3] != 1 {
		return fmt.Errorf("SOCKS UDP associate failed: %v, %v", reply, err)
	}
	relay := &net.UDPAddr{IP: net.IP(reply[4:8]), Port: int(binary.BigEndian.Uint16(reply[8:10]))}
	if relay.Port == 0 {
		return fmt.Errorf("SOCKS UDP associate returned zero relay port")
	}
	udp, err := net.ListenUDP("udp4", &net.UDPAddr{IP: source.To4()})
	if err != nil {
		return err
	}
	defer udp.Close()
	if err := udp.SetDeadline(time.Now().Add(10 * time.Second)); err != nil {
		return err
	}
	echoHost, _, err := net.SplitHostPort(os.Getenv("PHOTON_PHASE8_ECHO"))
	if err != nil {
		return err
	}
	target := &net.UDPAddr{IP: net.ParseIP(echoHost).To4(), Port: 8080}
	query := []byte{0x50, 0x58, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 5, 's', 'm', 'o', 'k', 'e', 6, 'p', 'h', 'o', 't', 'o', 'n', 0, 0, 1, 0, 1}
	packet := append(phase8SOCKSUDPHeader(target), query...)
	if _, err := udp.WriteToUDP(packet, relay); err != nil {
		return err
	}
	response := make([]byte, 512)
	n, sourceAddr, err := udp.ReadFromUDP(response)
	if err != nil {
		return err
	}
	if !sourceAddr.IP.Equal(relay.IP) || sourceAddr.Port != relay.Port {
		return fmt.Errorf("SOCKS UDP reply source = %s, want relay %s", sourceAddr, relay)
	}
	responseTarget, dns, err := parsePhase8SOCKSUDPDatagram(response[:n])
	if err != nil {
		return err
	}
	if !responseTarget.IP.Equal(target.IP) || responseTarget.Port != target.Port {
		return fmt.Errorf("SOCKS UDP response target = %s, want %s", responseTarget, target)
	}
	if len(dns) < 12 || dns[0] != query[0] || dns[1] != query[1] || dns[2]&0x80 == 0 || binary.BigEndian.Uint16(dns[6:8]) != 2 {
		return fmt.Errorf("invalid DNS response ID/answers: %x", dns)
	}
	return nil
}

func runPhase8Command(t *testing.T, ctx context.Context, name string, args ...string) {
	t.Helper()
	output, err := exec.CommandContext(ctx, name, args...).CombinedOutput()
	if err != nil {
		t.Fatalf("%s %s: %v\n%s", name, strings.Join(args, " "), err, output)
	}
}

// Docker bind mounts are resolved by the daemon. When this smoke itself runs
// inside a privileged test container, its Go test binary is normally under the
// container-only /tmp. PHOTON_SERVICES_SMOKE_BIND_DIR points at a host-visible
// bind mount (for example /work/.phase8-smoke) and makes the helper available
// to the host Docker daemon as well.
func phase8DockerVisibleHelper(suffix string) (string, bool, error) {
	current, err := filepath.Abs(os.Args[0])
	if err != nil {
		return "", false, err
	}
	dir := os.Getenv("PHOTON_SERVICES_SMOKE_BIND_DIR")
	if dir == "" {
		return current, false, nil
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", false, err
	}
	target := filepath.Join(dir, "photon-services-phase8-"+suffix)
	in, err := os.Open(current)
	if err != nil {
		return "", false, err
	}
	defer in.Close()
	out, err := os.OpenFile(target, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o755)
	if err != nil {
		return "", false, err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		_ = os.Remove(target)
		return "", false, err
	}
	if err := out.Close(); err != nil {
		_ = os.Remove(target)
		return "", false, err
	}
	return target, true, nil
}

func phase8DeleteDockerUserRule(tag string) {
	output, err := exec.Command("nft", "-a", "list", "chain", "ip", "filter", "DOCKER-USER").CombinedOutput()
	if err != nil {
		return
	}
	for line := range strings.SplitSeq(string(output), "\n") {
		if !strings.Contains(line, "comment \""+tag+"\"") {
			continue
		}
		marker := "# handle "
		index := strings.LastIndex(line, marker)
		if index < 0 {
			continue
		}
		handle := strings.TrimSpace(line[index+len(marker):])
		if handle != "" {
			_ = exec.Command("nft", "delete", "rule", "ip", "filter", "DOCKER-USER", "handle", handle).Run()
		}
		return
	}
}

func readPhase8Forwarding(t *testing.T) string {
	t.Helper()
	data, err := os.ReadFile("/proc/sys/net/ipv4/ip_forward")
	if err != nil {
		t.Fatal(err)
	}
	return strings.TrimSpace(string(data))
}

func writePhase8BirdConfig(t *testing.T, path, config string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(config), 0o600); err != nil {
		t.Fatal(err)
	}
}

func startPhase8Bird(t *testing.T, ctx context.Context, netns, config, socket, pid string) {
	t.Helper()
	if output, err := exec.CommandContext(ctx, "ip", "netns", "exec", netns, "bird", "-c", config, "-s", socket, "-P", pid).CombinedOutput(); err != nil {
		t.Fatalf("start BIRD in %s: %v\n%s", netns, err, output)
	}
	deadline := time.Now().Add(10 * time.Second)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(socket); err == nil {
			return
		}
		time.Sleep(100 * time.Millisecond)
	}
	t.Fatalf("BIRD control socket %s did not appear", socket)
}

func stopPhase8Bird(socket string) {
	_ = exec.Command("birdc", "-s", socket, "down").Run()
}

func waitPhase8BirdRoute(t *testing.T, ctx context.Context, socket, prefix string) {
	t.Helper()
	deadline := time.Now().Add(20 * time.Second)
	for time.Now().Before(deadline) {
		output, err := exec.CommandContext(ctx, "birdc", "-s", socket, "show", "route", prefix).CombinedOutput()
		if err == nil && strings.Contains(string(output), prefix) {
			return
		}
		time.Sleep(250 * time.Millisecond)
	}
	t.Fatalf("BIRD %s did not learn %s", socket, prefix)
}

func waitPhase8TCP(ctx context.Context, address string) error {
	deadline := time.Now().Add(15 * time.Second)
	for time.Now().Before(deadline) {
		conn, err := (&net.Dialer{Timeout: time.Second}).DialContext(ctx, "tcp", address)
		if err == nil {
			_ = conn.Close()
			return nil
		}
		time.Sleep(200 * time.Millisecond)
	}
	return fmt.Errorf("service %s did not become ready", address)
}

func assertPhase8Route(t *testing.T, ctx context.Context, netns, address, want string) {
	t.Helper()
	args := []string{"route", "get", address}
	if netns != "" {
		args = append([]string{"netns", "exec", netns, "ip"}, args...)
	}
	output, err := exec.CommandContext(ctx, "ip", args...).CombinedOutput()
	if err != nil || !strings.Contains(string(output), want) {
		t.Fatalf("ip %s: %v\n%s\nwant %q", strings.Join(args, " "), err, output, want)
	}
}
